# Build settings

port: 4000
markdown:  kramdown
permalink: /:title
plugins:   [jekyll-sitemap, jekyll-feed,  jekyll-seo-tag]

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)

title:		   "Loops by Lois"
description: " A cheerful journal of crochet creations by Lois — sharing patterns, ideas, and the joy of making something by hand."
author:      "Paul Le"
